# Generated by Django 4.2.4 on 2023-10-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0002_search_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="search",
            name="response",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
