# Generated by Django 4.2.4 on 2023-10-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0003_search_response"),
    ]

    operations = [
        migrations.AlterField(
            model_name="search",
            name="response",
            field=models.CharField(default="", max_length=100),
        ),
    ]
